load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "adcInterface",
    srcs = [],
    hdrs = [
        "IAdc.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hw:pins",
    ],
)

cc_library(
    name = "i2cInterface",
    srcs = [],
    hdrs = [
        "II2c.hh",
    ],
    visibility = ["//visibility:public"],
)
