cc_library(
    name = "msgs",
    hdrs = [
      "Battery.hh",
      "Compass.hh",
      "Depth.hh",
      "Header.hh",
      "Imu.hh",
      "Type.hh"
    ],
    visibility = ["//visibility:public"]
)
