load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "logger",
    srcs = ["logger.cc"],
    hdrs = ["logger.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "@spdlog",
    ],
)
